### PR TITLE
Ensure components list is scrollable

### PR DESCRIPTION
**Pull request by karlbright**
**This PR makes some layout and style changes to the default style guide output**

styleguidist-scrolling

My existing codebase has a large number of components, running styleguidist on this results in a list of components that is not scrollable do the "sticky" functionality that currently exists.

This PR makes changes to the layout to ensure that the component list is always scrollable. The component list has been moved to the left of the screen due to the fact that there is a max-width on the styleguide(which i think is important) and implementing scrolling functionality with that given layout felt odd. It wasn't clear that you could scroll the components list, this approach goes for something a little more "traditional" as far as documentation styling goes.

image

### CODE REVIEW

**Comment by mik01aj** [comment]
Does it also fix #68?

**Comment by karlbright** [comment]
@mik01aj Damn, i was JUST about to add that comment :)

**Comment by mik01aj** [comment]
LGTM, I like the simplification.

**Comment by sapegin** [comment]
Cool, thanks! The only problem is now it’s shifted to the left side of the window which looks terrible on a big screen:

**Comment by sapegin** [comment]
How about [something like this](http://styleguide.cfapps.io/react_components_autocomplete.html)?



Sidebar is on the left but the main area is centered. I also like the style guide title inside the sidebar.

**Comment by karlbright** [comment]
I'm all for the title in the sidebar :+1:

**Comment by karlbright** [comment]
image

**Comment by sapegin** [comment]
Nice!

**Pull request merged**
