### PR TITLE
added support for import statements in code examples

### PR DESCRIPTION
**Pull request by ctoscano**
Added support for import statements so that code examples and component definitions can keep the same code style.

### CODE REVIEW

**Comment by sapegin** [comment]
Very cool, thanks!

Could you please update the readme too: https://github.com/sapegin/react-styleguidist#writing-code-examples

**Comment by mik01aj** [comment]
Waaait... I'm not sure we actually need to match `import` statements. Babel should transpile `import` to `require`.

**Comment by ctoscano** [comment]
@sapegin: I added the example to Readme.md#writing-code-exmaples. 

@mik01aj: While I agree with you, that would cost a broader re-write and re-evaluating an unknown number of previously made design decisions. If you know the code well enough to point out where the change should be made I can take a closer look, if you think it is worth it.

**Comment by mik01aj** [comment]
Ah, I see the loader doesn't transpile the code, it's transpiled in runtime. So this would mean adding additional transpilation step to the loader, only to parse the requires. So maybe you're right, it's just practical to handle imports this way. But, could you please add unit tests to make sure that it works reasonably well for these cases:

```
import { square, diag } from 'lib';
import * as lib from 'lib';
import myFunc from 'myFunc';
import MyClass from 'MyClass';
import _, { each } from 'underscore';
import { default as foo } from 'lib';
import foo from 'lib';
import * as lib from 'lib';
import { inc, counter } from 'lib';
import theDefault, { named1, named2 } from 'src/mylib';
import theDefault from 'src/mylib';
import { named1, named2 } from 'src/mylib';
import { named1 as myNamed1, named2 } from 'src/mylib';
import * as mylib from 'src/mylib';
import 'src/mylib';
```

(Source: http://www.2ality.com/2014/09/es6-modules-final.html)

**Comment by sapegin** [comment]
+1 for unit tests.

**Comment by sapegin** [comment]
Closing it for now. Feel free to reopen with tests.

**Pull request closed without merging**
