### PR TITLE
Added support for using require(...) in code examples.

### PR DESCRIPTION
**Pull request by mik01aj**
@sapegin, I need your help with testing this code. And I wait for any other comments. ;)

### CODE REVIEW

**Comment by mik01aj** [comment]
I thought more about it, and it should be actually possible to infer the right context from the example code. And for sure this would also be the cleanest way to do it.

**Comment by sapegin** [comment]
That would be very nice because now it’s hard to understand.

**Comment by mik01aj** [comment]
Well, I researched this a bit, but apparently webpack doesn't expose its internal behaviour of creating a require contect containing whatever the module needs. [The context API](https://webpack.github.io/docs/context.html) lets me create a context giving a regex, so I could look for `/require\s*\((.*)\)/` in the example code and make a regex that would match any of the found strings and nothing else, but this seems clunky. It will work, and I can provide some friendly error handling so it won't bite the users much. Maybe it's still better than adding the hardly understandable config option.

What do you think?

**Comment by sapegin** [comment]
I think it’s much better ;-)

**Comment by mik01aj** [comment]
Okay, see the new commit.

I'd add some tests for my helper functions but I don't see any test framework installed. Could you take care of this?

**Comment by sapegin** [comment]
Cool! I’ll add Mocha soon.

**Comment by mik01aj** [comment]
Check my new commit `facceef`! :)

**Comment by sapegin** [comment]
Mocha is here!

**Comment by mik01aj** [comment]
I thought about it again and I realized that I don't need the webpack's `context` at all. The `context` had also one drawback: requires of stuff from `../` didn't work. My new solution is simpler and cleaner, and requiring anything just works.

I still didn't add any tests, but I don't know what exactly could I test. Please look at the code and tell me if you feel like some part of it might break in the future.

**Comment by sapegin** [comment]
Cool, thanks!

About tests:

1. Complex regexps could be tested. It probably means extracting extracting them to utils.
2. I thinks we can test that loader returns valid JavaScript (try to compile it with Babel?).

**Comment by mik01aj** [comment]
> extracting them to utils

This is harder than I thought because the loader is in ES5 and utils are ES6.

**Comment by sapegin** [comment]
Or you can just export these function from the loader and use them in tests.

**Comment by mik01aj** [comment]
That's what I do:

```
module.exports = _.assign(exampleLoader, {
	requireAnythingRegex: requireAnythingRegex,
	simpleStringRegex: simpleStringRegex,
	readExamples: readExamples,
	findRequires: findRequires,
});
```

Btw, there's a simpler way to check JS (ES5) validity: http://www.ecma-international.org/ecma-262/5.1/#sec-15.3.2.1

**Comment by sapegin** [comment]
Cool! And a simpler way is always better ;-)

**Comment by mik01aj** [comment]
Done!

**Comment by sapegin** [comment]
Cooooool!

**Comment by mik01aj** [comment]
commit updated, ihmo it's good to merge now.

**Comment by sapegin** [comment]
Thank you very much!

:shipit:

**Pull request merged**
