### PR TITLE
Add fuzzy search to Table Of Contents

### PR DESCRIPTION
**Pull request by zammer**
Add fuzzy search to Table Of Contents

fuzzysearch

### CODE REVIEW

**Comment by mik01aj** [comment]
@zammer thanks for the PR, I love the feature! But please look at the comments in the source code. (Maybe you'd like to wait for more input from @sapegin before you start fixing it).

**Comment by mik01aj** [comment]
@zammer please also fix the [reported ESLint errors](https://travis-ci.org/sapegin/react-styleguidist/jobs/113362957#L512)!

**Comment by sapegin** [comment]
And thanks for the PR @zammer!

**Comment by zammer** [comment]
No worries.

Leave it with me.

**Comment by oliverturner** [comment]
Shouldn't 
`const regex = new RegExp(value.toLowerCase().toString(), 'g');` 
be 
`const regex = new RegExp(value.toString().toLowerCase(), 'g');`
instead? A value that isn't a string already will throw if `toLowerCase` is called on it...

**Comment by zammer** [comment]
@sapegin and @mik01aj refactored as requested.

**Comment by mik01aj** [comment]
LGTM :shipit:

**Comment by sapegin** [comment]
I’ll tweak it a bit later. Congrats with the first pull request!

:confetti_ball: :confetti_ball: :confetti_ball: :confetti_ball: :confetti_ball:

**Comment by zammer** [comment]
Thankyou

**Pull request merged**
