### PR TITLE
Improve table of contents usability

### PR DESCRIPTION
**Pull request by smashercosmo**
Added possibility to open component in isolated view from the sidebar menu

Demo

### CODE REVIEW

**Comment by mik01aj** [comment]
doesn't the arrow create an empty line with longer component names?

**Comment by smashercosmo** [comment]
Sorry, can't really understand the question)

**Comment by mik01aj** [comment]
I mean that when the component has a long name, like `CampaignsOverviewPageLoader` or so, the arrow might not be visible, or it might even wrap to the next line. And as you use `display: none` for toggling the arrow, it will make the stuff below jump one line down/up on mouse enter/leave.

**Comment by smashercosmo** [comment]
Yes, the arrow will jump to the next line, but it won't make component names jump, because it has position: absolute. Although, that's also not very beautiful. Any ideas how to improve it?

**Comment by smashercosmo** [comment]
We can place link to isolated view on the left side of component name. But in that case I think the icon should be different. Something like [external link icon](http://fontawesome.io/icon/external-link/).

**Comment by mik01aj** [comment]
You could put `white-space: nowrap` on the `<li>`. I also wonder why did you need `position: absolute`...

**Comment by smashercosmo** [comment]
If you put ```white-space: nowrap``` then in case of long component name arrow becomes completely invisible. ```position: absolute``` removes external link from the flow, so it doesn't affect vertical alignment of component name and external link. If you remove ```position: absolute``` you'll see how lines jump.

**Comment by sapegin** [comment]
`display:none` is not the best way to show things anyway. `opacity` with animation like in the examples would be better. I’d just make them `display:inline` instead of `position:absolute`.

**Comment by mik01aj** [comment]
@smashercosmo I don't think it's a big problem if they become invisible.

And honestly, I don't see a big improvement coming from this PR. Imagine, the user comes for a first time, clicks, some innocent-looking arrow and the navigation disappears. The current behaviour is at least consistent and it's easier to go back.

**Comment by sapegin** [comment]
Yeah, I’m also not sure whether it makes UI better of worse ;-)

**Comment by smashercosmo** [comment]
No problem) Feel free to close. Just thought it's useful, when user (if he has a lot of components) don't have to scroll down to the end of the page to be able to open component in isolated view.

**Comment by sapegin** [comment]
No need to scroll, just one extra click ;-)

**Comment by smashercosmo** [comment]
Yep)) You're right. Then again: feel free to close) Anyway, thx for discussion.

**Comment by smashercosmo** [comment]
@sapegin by the way: simple ```display: inline``` will affect line height.

**Pull request closed without merging**
