### PR TITLE
Update React dependency to 15.0.0

### PR DESCRIPTION
**Pull request by saiichihashimoto**
To work with any new react project, this needs to be updated to use the newer versions of React.

### CODE REVIEW

**Comment by saiichihashimoto** [comment]
I'm having a hard time understanding these error messages.... a little help? :-P

**Comment by cameronrohani** [comment]
+1

**Comment by sapegin** [comment]
`>=0.14.0` already includes 15.x, works fine for me with React 15.0

**Comment by saiichihashimoto** [comment]
Hmmm, I updated my npm and now I can't recreate the error. Closing.

**Pull request closed without merging**
