### PR TITLE
Unique alias for components to avoid conflicts with host projects

### PR DESCRIPTION
**Pull request by sunesimonsen**
Fixes: #42 

I have tested the examples and ran the tests, but please make sure that things seems okay before merging.

Kind regards
Sune

### CODE REVIEW

**Comment by mik01aj** [comment]
LGTM :shipit:

**Comment by sapegin** [comment]
Looks like Travis has some problems. Don’t know how to restart the job.

**Comment by sunesimonsen** [comment]
Thanks.

**Comment by sunesimonsen** [comment]
@sapegin thanks for merging, do you know when the merged features will be released?

**Comment by sapegin** [comment]
[I know](https://github.com/sapegin/react-styleguidist/releases/tag/1.2.1) ;-)

**Comment by sunesimonsen** [comment]
Awesome thanks!

**Comment by sapegin** [comment]
Thanks for your contributions!

**Pull request merged**
