### PR TITLE
added support for named export

### PR DESCRIPTION
**Pull request by pvasek**
This is attempt to fix issue #37. I chose the simple method described in the issue. Sorry, could not figure out the where I should put the resolver. It seems there is a lot of magic going on :) 

I could not find any unit tests for this code. Could you point me out where I can find them?

### CODE REVIEW

**Comment by mik01aj** [comment]
The test for examples loader is in [`examples.loader.spec.js`](https://github.com/sapegin/react-styleguidist/blob/master/test/examples.loader.spec.js).

I'd say :-1: for adding a new config option. Ideally it should "just work" without any config (I think it's easy to detect that the exported component is not the default export).

I also wonder how does this relate to https://github.com/sapegin/react-styleguidist/pull/106 (I haven't tested that one). I mean, if you don't want to `export default` something, then it's probably because you have something more in this file, so isn't this case already served by that pull request?

**Comment by sapegin** [comment]
I agree that a new option is not good.

**Comment by pvasek** [comment]
OK, no problem, I will try a different approach.

I think #106 solved the first part of the problem, to get props information for these components.

Could you point me out where is a good place to do that work. I am still quite confused how it works :) Thanks

**Comment by mik01aj** [comment]
See this PR: https://github.com/sapegin/react-styleguidist/pull/104. If you could write unit tests for it, you could use the ES6 `import` in your example code. Do you need anything more?

**Comment by pvasek** [comment]
OK, I will check it. Thank you!

**Comment by pvasek** [comment]
Turned outs, it was actually related to #104. Because in that case I can use named export and default export together. I just didn't realize that it hasn't been released yet. Sorry to bother you and thank you once again.

**Comment by sapegin** [comment]
Does it mean that we can close #37 and this PR?

**Comment by pvasek** [comment]
I have already closed this PR. PR #106 solves completely if you have the same component as named and default as well. 

The #37 is probably more connected to the fact that the example component is always the default exported one. In that case the #104 could probably be a solution or at least workaround.

**Pull request closed without merging**
