### PR TITLE
Update babel-preset-react-hmre to v1.1.1

### PR DESCRIPTION
**Pull request by danmartinez101**
Contributes to potentially closing #116

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks!

**Comment by albertfdp** [comment]
@sapegin Can you push a npm version so we can pick this? Thanks!

**Comment by sapegin** [comment]
@albertfdp Done, with lots of changes ;-)

**Comment by albertfdp** [comment]
Awesome, thanks!

**Pull request merged**
