### PR TITLE
Added "defined in file ..." information for the components.

### PR DESCRIPTION
**Pull request by mik01aj**
Looks like this:

image

The shown path is relative to `config.rootDir`.

### CODE REVIEW

**Comment by sapegin** [comment]
Nice! Do we really need this “defined in”? I think just path is enough.

**Comment by mik01aj** [comment]
Maybe not. I can remove it.

**Comment by mik01aj** [comment]
Btw. I did some other style changes: bold headers and bigger margins between components.

**Comment by sapegin** [comment]
Bigger margins: +1.
Bold headers: –1 ;-)

It’d be nice to make styleguide themable though.

**Comment by mik01aj** [comment]
So, how do you like the updated commit?

**Comment by mik01aj** [comment]
So, how do you like the updated commit?

**Comment by sapegin** [comment]
Almost ;-) Why do you need margin-top instead of margin-bottom?

**Comment by mik01aj** [comment]
to put some space before the first component. It doesn't do anything for subsequent components because of margin collapsing.

**Comment by sapegin** [comment]
But it’s the same as margin-bottom on the header.

**Comment by sapegin** [comment]
```
<header>
  <h2/>
  <div>description</div>
</header>
```

```
.header {
  margin-bottom: 1rem;
}
```

**Comment by mik01aj** [comment]
I'm not sure we're talking about the same thing. Here's what I did:

image

**Comment by sapegin** [comment]
Yes, about the same thing. The problem is: you introduced margin-top, which, I believe should (and can) be avoided.

**Comment by mik01aj** [comment]
Got it! :) Check the new commit :)

**Comment by sapegin** [comment]
Cool, thanks!

**Pull request merged**
