### PR TITLE
Nicer formatting for the README documentation.

### PR DESCRIPTION
**Pull request by mik01aj**
I find the current README hard to read because there is so much white space and the page is so long. This PR is my approach to improve readability.

You can see how it looks like at https://github.com/lovelybooks/react-styleguidist/blob/readme-formatting/Readme.md

### CODE REVIEW

**Comment by sapegin** [comment]
Whitespace is good ;-) But I like your changes.

**Comment by mik01aj** [comment]
@sapegin Looks like your editor removed the significant whitespace in https://github.com/sapegin/react-styleguidist/commit/0627af5159bb23f3aeeb3bd2ddbb304f3c3aa42a...

**Comment by sapegin** [comment]
That’s because your editor do not use EditorConfig ;-) I hate this feature of Markdown actually but I’ll revert my changes and change EditorConfig settings.

**Comment by mik01aj** [comment]
If you don't like double spaces we can use explicit `<br>`.

**Comment by sapegin** [comment]
Much better ;-)

**Comment by mik01aj** [comment]
:+1:

**Pull request merged**
