### PR TITLE
Make css modules class names unique

### PR DESCRIPTION
**Pull request by sunesimonsen**
I have a problem where I use a css module style called `container` in my components, but that conflicts with the styleguide styles. Add a hash to make the class names unique.

### CODE REVIEW

**Comment by mik01aj** [comment]
These names were added because of https://github.com/sapegin/react-styleguidist/issues/32#issuecomment-157875674.

And I don't understand where you're having conflicts, because all the class names are already prefixeds with `ReactStyleguidist-`.

**Comment by sunesimonsen** [comment]
Because my components uses css modules and are loaded by the postcss loader configured in react-styleguides

**Comment by sunesimonsen** [comment]
This line adds the config.rootDir to the includes of the postcss loader: https://github.com/sapegin/react-styleguidist/blob/master/src/make-webpack-config.js#L183

Here you can see that the rootDir is parts of the includes: https://github.com/sapegin/react-styleguidist/blob/master/src/make-webpack-config.js#L18

Am I misunderstanding something here, or should `rootDir` point to the directory where your components live?

**Comment by sunesimonsen** [comment]
@mik01aj I see, it is actually a feature that you can override the styles, so they should not be unique. But then I would like the postcss loader to keep its hands of my components and I can add my own loader.

I might just confused about how the `rootDir` should be used, because right now it prefixes my components with `ReactStyleguidist-`.

Sorry for noise if I'm just wrong.

**Comment by mik01aj** [comment]
Ah, so *that's* the bug. Your components shouldn't be prefixed. I suppose it's a problem with the webpack config.

**Comment by sunesimonsen** [comment]
@mik01aj I basically want to control the css loading for my own components.

**Comment by sunesimonsen** [comment]
I'll close this PR and make an issue for that instead.

**Comment by sapegin** [comment]
CSS loader was enabled for your components folder by mistake :-) I’ll fix that in the next release.

**Comment by sunesimonsen** [comment]
Thanks that sounds great.

**Comment by sunesimonsen** [comment]
@sapegin I'll just make an issue for that, so it isn't forgotten.

**Comment by sunesimonsen** [comment]
@sapegin https://github.com/sapegin/react-styleguidist/issues/62

**Pull request closed without merging**
